# Generated by Django 5.1.1 on 2024-11-14 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions_accuracy', models.TextField(blank=True, null=True)),
                ('app_usability', models.TextField(blank=True, null=True)),
                ('user_interface', models.TextField(blank=True, null=True)),
                ('helpful_info', models.TextField(blank=True, null=True)),
                ('app_recommend', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
