# Generated by Django 5.1.1 on 2024-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_recent_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='get_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
