# Generated by Django 5.1.2 on 2024-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_home", "0008_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp_code",
            field=models.CharField(max_length=4),
        ),
    ]
