# Generated by Django 5.1.2 on 2024-12-05 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_home", "0009_alter_otp_otp_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
